[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'examples', 'unsafe']
ffi = true

# Compilation
evm_version = "shanghai"
solc_version = "0.8.23"
via_ir = true
optimizer = false
extra_output_files = ["irOptimized"]

[fmt]
line_length = 80
int_types = "short"
number_underscore = "preserve"

[doc]
out = "docs_generated" # Note to not overwrite own docs

# Profile to compile without --via-ir and optimizations
# Run via `FOUNDRY_PROFILE=light forge ...`
[profile.light]
via_ir = false
optimizer = false

# Profile to compile with --via-ir and optimizations
# Run via `FOUNDRY_PROFILE=release forge ...`
[profile.release]
via_ir = true
optimizer = true
optimizer_runs = 100_000

# Profile for intense testing
# Run via `FOUNDRY_PROFILE=intense forge t`
[profile.intense.fuzz]
runs = 10_000

# Profile for ci testing
# Run via `FOUNDRY_PROFILE=ci forge t`
[profile.ci]
via_ir = true
optimizer = true
optimizer_runs = 100_000
[profile.ci.fuzz]
runs = 10_000
[profile.ci.invariant]
runs = 10_000
